FROM mcr.microsoft.com/playwright/python:v1.53.0-noble

WORKDIR /app

RUN set -e; \
        for i in 1 2 3; do apt-get update && break || sleep 3; done; \
        apt-get install -y --no-install-recommends \
            fluxbox \
            x11vnc \
            novnc \
            websockify \
            && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --no-cache-dir --upgrade --ignore-installed requests selenium playwright==1.53.0

COPY dummy_bot /app
RUN chmod +x /app/start_bot_vnc.sh

CMD ["/bin/bash", "/app/start_bot_vnc.sh"]
